---
name: build

on:
  push:
    branches:
    - '*'
    tags:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  build-using-nix:
    name: Build using nix environment
    runs-on: self-hosted

    steps:
      - name: git checkout
        uses: actions/checkout@v3.1.0

      - name: nix, install
        uses: DeterminateSystems/nix-installer-action@main

      - name: nix, cache
        uses: DeterminateSystems/magic-nix-cache-action@v1

      - name: check code integrity
        run:  nix develop --command make check

  build-using-docker:
    name: Build using docker environment
    runs-on: self-hosted
    container: ghcr.io/openmpdk/spex/spex-env:latest

    steps:
    - name: git checkout
      uses: actions/checkout@v3.1.0

    - name: install
      run: make
