---
name: build-docker-env

on:
  push:
    branches:
    - 'main'
    - 'test-docker'

    tags:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  # image: "spex"
  build-docker-spex:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

    env:
      image_name: ghcr.io/openmpdk/spex

    steps:
    - name: Retrieve spex
      uses: actions/checkout@v3.1.0

    - name: nix, install
      uses: DeterminateSystems/nix-installer-action@main

    - name: nix, cache
      uses: DeterminateSystems/magic-nix-cache-action@v1

    - name: env, set sha_short
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

    - name: nix, build docker nixenv
      run: |
        nix build .#dockerImage

    - name: docker, load image
      run: |
        docker load -i result

    - name: docker, tag image
      run: |
        docker tag spex:${{ env.sha_short }} ${{ env.image_name }}:${{ env.sha_short }}
        docker tag spex:${{ env.sha_short }} ${{ env.image_name }}:${{ github.ref_name }}

    - name: Log into GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push to ghcr.io
      run: |
        docker push ${{ env.image_name }}:${{ env.sha_short }}
        docker push ${{ env.image_name }}:${{ github.ref_name }}

  # image: "spex-devenv"
  build-docker-spex-devenv:
    runs-on: ubuntu-22.04
    env:
      image_name: ghcr.io/openmpdk/spex-devenv

    strategy:
      fail-fast: true

    steps:
    - name: git checkout
      uses: actions/checkout@v3.1.0

    - name: env, set sha_short
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

    - name: env, set DOCKER_IMAGE_TAG
      run: |
        echo "DOCKER_IMAGE_TAG=${{ env.sha_short }}" >> "$GITHUB_ENV"

    - name: docker, build
      run: |
        make dev-docker-build

    - name: docker, tag image
      run: |
        docker tag ${{ env.image_name }}:${{ env.sha_short }} ${{ env.image_name }}:${{ github.ref_name }}

    - name: Log into GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push to ghcr.io
      run: |
        docker push ${{ env.image_name }}:${{ env.sha_short }}
        docker push ${{ env.image_name }}:${{ github.ref_name }}

  verify-docker-spex-devenv:
    needs: build-docker-spex-devenv
    runs-on: ubuntu-22.04
    env:
      image_name: ghcr.io/openmpdk/spex-devenv

    strategy:
      fail-fast: false

    steps:
    - name: git checkout
      uses: actions/checkout@v3.1.0

    - name: env, set sha_short
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

    - name: check
      run: >
        docker run --rm
        -w /tmp/spex
        --mount type=bind,source="${{ github.workspace}}",target=/tmp/spex
        ${{ env.image_name }}:${{ env.sha_short }}
        nix develop .# --command
        make check

    - name: docs
      run: >
        docker run --rm
        -w /tmp/spex
        --mount type=bind,source="${{ github.workspace}}",target=/tmp/spex
        ${{ env.image_name }}:${{ env.sha_short }}
        nix develop .# --command
        make docs
